# Generated by Django 4.0 on 2022-07-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_events_eventyear_alter_events_eventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='blog_images')),
                ('date_time', models.DateTimeField()),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.events')),
            ],
        ),
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.events')),
            ],
        ),
    ]
