# Generated by Django 4.0 on 2022-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_images_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
