# Generated by Django 4.0.6 on 2022-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_event_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
