# Generated by Django 4.0.6 on 2022-09-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_remove_images_image_images_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='field_name',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/event_images'),
        ),
    ]
