# Generated by Django 4.0.6 on 2023-06-30 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0017_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 30, 20, 28, 37, 612723)),
        ),
    ]
